lib/drives/forms/create_drive_form.dart, pubspec.lock, pubspec.yaml
changed the format for the time and date fields. 
https://discord.com/channels/1034566655826735135/1046477068705222736/1046477136032190485
@Eddie-42 thanks for the report.
=> [BUG FIX] fixed time and date format 

.gitignore, .vscode/settings.json, lib/account/models/profile.dart, lib/drives/forms/create_drive_form.dart, lib/drives/models/drive.dart, lib/main.dart, lib/main_app.dart, lib/rides/models/ride.dart, lib/util/loading_button.dart, lib/util/own_theme_fields.dart, lib/welcome/pages/login_page.dart, lib/welcome/pages/reset_password_page.dart, lib/welcome/pages/welcome_page.dart
Changed the line length for dart to 120 (seems like a good value to me, what do you think?) Then I ran `dart format . --line-length=120`.
We definitely have a lot more space to work with now!
I changed the value in the VSCode configuration so it should be applied automatically there, but you should also change it in Android Studio if you use it (search for "Dart line length" in the settings).
=> Line length 120

android/app/src/main/AndroidManifest.xml, lib/drives/forms/create_drive_form.dart, lib/main.dart, lib/util/motis_handler.dart, lib/util/search/address_search_delegate.dart, lib/util/search/address_search_field.dart, lib/util/search/address_suggestion.dart, lib/util/search/position.dart
Adds search suggestions to the address field:
- Search field goes to app bar, results go to body (uses native `SearchDelegate`)
- AdressSuggestions are sourced from Motis via http call (does not seem to support street addresses? we will have to ask about that)
- Also saves the whole address inside the form state, maybe we should use that instead of the short name
Sorry @MarkFalke if you had done anything on this already
=> Address suggestions

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcworkspace/contents.xcworkspacedata
i moved the ios files from the other PR to a new one. 
@fynsta thanks for the reminder
=> add autogenerated ios files

.fvm/fvm_config.json, .gitignore, .vscode/settings.json
with the flutter version manager (fvm) it's easy to change the flutter versions and make sure that we are all working with the same one. 
I think at the moment it's not important, but since i had a different version installed than all of you what lead to the problems with my last PR i installed it so that this does not happen again. (for more information see [here](https://fvm.app/)).
@fynsta thanks for finding fvm.
=> add flutter version manager

lib/account/models/profile.dart, lib/account/models/profile_feature.dart, lib/account/models/review.dart, lib/account/pages/account_page.dart, lib/account/pages/write_review_page.dart, lib/drives/models/drive.dart, lib/drives/pages/drive_detail_page.dart, lib/rides/models/ride.dart, lib/rides/pages/ride_detail_page.dart, lib/util/big_button.dart, lib/util/custom_banner.dart, lib/util/model.dart, lib/util/profiles/custom_rating_bar_indicator.dart, lib/util/profiles/profile_chip.dart, lib/util/profiles/profile_row.dart, lib/util/profiles/profile_widget.dart, lib/util/profiles/profile_wrap_list.dart, lib/util/profiles/reviews/custom_rating_bar.dart, lib/util/profiles/reviews/custom_rating_bar_indicator.dart, lib/util/profiles/reviews/custom_rating_bar_size.dart, lib/util/review_detail.dart, lib/util/trip/ride_card.dart, lib/util/trip/trip.dart, lib/util/trip/trip_overview.dart, pubspec.lock, pubspec.yaml
Sorry this got so big again! This adds a lot of stuff:
- Ride detail view
- Ride state (in place of boolean `approved` there are now multiple options)
- Ride and drive cancellation
- Banners to show important things about the state of ride and drive
- Profile attributes (full name, gender, age, ...). Those are not shown anywhere yet.
- "ProfileChip" for better profile display
- Profile Features (smoking, pets, children, drive style, music, ...)
- Reviews and a "WriteReview"-Page (reviews have one big rating, and then the 4 different category ratings as well as a text) including a RatingBar
Have fun reviewing!
Authored by @Eddie-42 and @fynsta
=> Ride detail

lib/drives/models/drive.dart, lib/drives/pages/create_drive_page.dart, lib/rides/models/ride.dart, lib/util/trip/trip.dart
change cancel in drive so that only pending & approved rides get updated 
fix ridesOfUserAtTime
fix previewFromDrive
add overlapsWithTime method to trip
=> fixes for ride and drive

.gitignore, l10n.yaml, lib/account/models/profile.dart, lib/drives/models/drive.dart, lib/drives/pages/create_drive_page.dart, lib/drives/pages/drive_chat_page.dart, lib/drives/pages/drive_detail_page.dart, lib/l10n/app_de.arb, lib/l10n/app_en.arb, lib/rides/models/ride.dart, lib/rides/pages/ride_detail_page.dart, lib/util/icon_widget.dart, lib/util/trip/pending_ride_card.dart, lib/util/trip/trip.dart, lib/util/trip/trip_overview.dart, pubspec.lock, pubspec.yaml
add Ride request 
add ride Approval/Reject
add DriveChatPage
add PendingRideCard
PushNotifications will be in another PR
co-authored by : @fynsta
=> Trip request processing

lib/rides/pages/search_suggestion_page.dart
I fixed the Time-/DatePicker for search suggestion page since they did not work at the moment. 
Thanks @Cedric for noticing.
=> fix Time-/DatePicker for search suggestion page

lib/drives/models/drive.dart, lib/drives/pages/create_drive_page.dart, lib/rides/models/ride.dart, lib/rides/pages/search_ride_page.dart, lib/rides/pages/search_suggestion_page.dart, lib/util/search/address_search_field.dart, lib/util/trip/trip.dart
@istzen here it is!!!!!
Now we finally actually store the address suggestion (name + position) in the database. This will not change anything on the surface, but would allow the algorithm to work correctly.
Note the ".toDouble" when getting the values from the database... dart is not smart enough to get a number via json and then cast it to double automatically.
=> Store addresses in database

lib/rides/pages/search_ride_page.dart, lib/rides/pages/search_suggestion_page.dart
Just a small bugfix we had talked about.
=> Give some time leniency

assets/logo.svg, ios/Podfile.lock, lib/account/pages/about_page.dart, lib/l10n/app_de.arb, lib/l10n/app_en.arb, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
An about page! I'm not too sure about the text (most of which would be better suited on a terms of service website). Also, I don't even know what a build signature is , but I'm sure all of you would agree that it looks cool and **VERY** professional (and chances are it could help developers if users experience bugs, I'm sure that's the sort of thing that goes into automated bug reports and since we don't have that, it can just be displayed here I guess).
=> Add about page

lib/rides/models/ride.dart
fix withdraw method in ride, the SupabaseManager. was missing in front of supabaseclient
=> fix withdraw method ride

lib/drives/pages/drive_chat_page.dart, lib/drives/pages/drive_detail_page.dart
as we discussed in our last Meeting i moved the pending rides from the driveChatPage to the driveDetailView.
=> refactor pending rides

.fvm/fvm_config.json
as i sad a short PR to change the version from 3.3.9 to 3.3.10
=> change version

lib/rides/models/ride.dart, lib/util/trip/pending_ride_card.dart
now we can really drop the RLS policy for the rides. Please aslo review the functions in supabase (approve_ride, reject_ride, is_update_allowed)
=> fix approve and reject ride

test/models/profile_feature_test.dart, test/models/profile_test.dart, test/models/report_test.dart, test/models/review_test.dart, test/util/factories/review_factory.dart
add unittests for profile_feature, report, review
=> Model Test, Review, Report, ProfileFeature

lib/drives/pages/drives_page.dart, lib/l10n/app_de.arb, lib/l10n/app_en.arb, lib/rides/models/ride.dart, lib/rides/pages/rides_page.dart, lib/util/trip/trip.dart, lib/util/trip/trip_page_builder.dart, lib/util/trip/trip_stream_builder.dart
Just a new text for every combination of ride/drive and past/upcoming. Along the way, I refactored the TripPageBuilder a little bit. It had way too many unnecessary arguments. I still think this is not perfect because there are some random type checks in there, but it's definitely a lot easier to read.
Also moves the logic for showing rides/drives in the list to the respective models. (I made it so that past pending rides are not shown anymore either, does everyone agree with that?)
Also the page is now a stateless widget, I don't know why it was just a class with a static build method?
=> Fix capitalization of "No rides" text

lib/account/pages/account_page.dart, lib/main_app.dart, test/widgets/flutter_test_config.dart, test/widgets/main_app_test.dart
Just 30 tested lines, but the tests are pretty satisfying this time.
=> Add tests for MainApp

lib/rides/models/ride.dart, lib/rides/pages/ride_detail_page.dart, test/util/factories/ride_factory.dart, test/widgets/drive_detail_page_test.dart, test/widgets/ride_detail_page_test.dart
Second try without broken diff
=> Add RideDetailPage tests

lib/drives/pages/create_drive_page.dart, lib/l10n/app_de.arb, lib/l10n/app_en.arb, lib/util/fields/increment_field.dart, lib/util/search/address_search_field.dart, lib/util/search/start_destination_timeline.dart, lib/util/trip/trip.dart
As we talked about, I redesigned the create drive page a bit (but without changing the functionality). A similar update to the search rides page is coming later.
=> Better create drive

lib/rides/pages/rides_page.dart, lib/util/trip/trip_page_builder.dart, lib/util/trip/trip_stream_builder.dart, test/util/factories/ride_factory.dart, test/widgets/drive_detail_page_test.dart, test/widgets/drives_page_test.dart, test/widgets/rides_page_test.dart, test/widgets/trip_page_builder_test.dart
add test for drivesPage and RidesPage, most of them i refactored into trip_page_builder_test since the code is the same that should not be a Problem.
=> Rides page/drives page tests

lib/util/snackbar.dart, lib/util/trip/pending_ride_card.dart, lib/util/trip/ride_card.dart, lib/util/trip/trip_card.dart, test/util/pump_material.dart, test/widgets/cards_test.dart
Tests for Cards, note that the coverage is not that good since we have no method to test the color if I am correct, otherwise please let me know then I'll add tests to check for the status color.
Add pumpScaffold method for all widgets that don't have a scaffold themselves.
=> Cards test

test/util/factories/drive_factory.dart, test/util/factories/ride_factory.dart, test/util/factories/trip_factory.dart
As talked about. If startTime is given, then endTime is generated from that. If endTime is given, then startTime is generated from that.
Also adds a convenience "duration" parameter, let's see if that one is useful.
=> Generate trip times better

lib/account/pages/profile_page.dart, lib/account/pages/reviews_page.dart, lib/account/widgets/review_detail.dart, lib/drives/pages/create_drive_page.dart, lib/main_app.dart, lib/rides/pages/ride_detail_page.dart, lib/rides/pages/search_ride_page.dart, lib/util/chat/pages/chat_page.dart, lib/util/profiles/profile_chip.dart, lib/util/profiles/profile_widget.dart, lib/util/profiles/profile_wrap_list.dart, lib/util/trip/ride_card.dart, lib/util/trip/trip_page_builder.dart, lib/welcome/pages/welcome_page.dart, test/widgets/main_app_test.dart
Add support for hero animations (see https://discord.com/channels/1034566655826735135/1065798676682903582)
=> Add support for hero animations in nested navigators

lib/rides/pages/search_ride_page.dart
Just a small PR so that in the search it's not possible anymore to request cancelled Drives.
=> change search

lib/account/pages/account_page.dart, test/widgets/settings/settings_page_test.dart
tests for the accountPage (SettingsPage in the Future). 
I did not test the launchUrlString method in the HelpPage/AboutPage we can do that later. And since there are no other relevant things to test in these Pages i just left them out. 
Also i moved the methods of the AccountPage below the build method as in the other pages.
=> Settings test

lib/util/locale_manager.dart, lib/util/search/address_suggestion_manager.dart, lib/util/storage_manager.dart, lib/util/theme_manager.dart, test/analysis_options.yaml, test/flutter_test_config.dart, test/managers/storage_manager_test.dart, test/models/chat_test.dart
Also adding the case for double and typing `readData` better
=> Test storageManager

lib/account/pages/about_page.dart, lib/account/pages/help_page.dart, lib/account/pages/reviews_page.dart, lib/drives/pages/create_drive_page.dart, lib/rides/models/ride.dart, lib/rides/pages/ride_detail_page.dart, lib/rides/pages/search_ride_page.dart, lib/util/fields/email_field.dart, lib/util/model.dart, lib/util/trip/pending_ride_card.dart, test/widgets/ride_detail_page_test.dart
- AG did not want TOS link
- Added correct "Withdraw button" text in FAQ
- added CopyWith for Ride and status/id, if needed please add for other models and attributes but that code is just not worth it right now
- removed unnecessary escapes in email regex
Removed all other todos because they were a little bit random. Of course we still need to add the algorithm, but we do not need to write that in the code. Same with notifications.
=> Cleans up remaining TODOS

lib/account/pages/write_review_page.dart
Suggestion came from a user study
=> Automatic overall review if category reviews given

scripts/coverage.sh
Only really relevant for @istzen. This should add support for fvm in the coverage script.
=> Fix script for fvm

.github/workflows/flutter-build.yml
Check that the file of untranslated messages is empty.
=> Verify translations

test/widgets/profile/edit_gender_page_test.dart, test/widgets/profile/edit_profile_features_page_test.dart
Some coverage was still missing sometimes because not enough values were hardcoded (this is together with this commit: https://github.com/MOTIS-Mitfahr-App/flutter-app/commit/17b99c222c2aef25848656fc2bbb891aba159e3a, which I pushed straight to main to avoid flakiness).
=> 100% coverage for edit tests

lib/drives/pages/create_drive_page.dart, lib/rides/pages/search_ride_page.dart, lib/util/fields/increment_field.dart
As discussed. I also added a little bit of padding on the SearchRidePage the card had a little bit of space around it, which was now missing.
=> Change increment field card to container

lib/util/profiles/reviews/aggregate_review_widget.dart
=> Fix the way aggregate review is shown

lib/rides/models/ride.dart, lib/rides/pages/search_ride_page.dart, lib/util/trip/ride_card.dart, test/models/position_test.dart, test/models/ride_test.dart, test/widgets/search_ride_page_test.dart
A little grab-bag of small improvements. 
And we fixed the ride search by reloading all possible drives when you change the date ( maybe flutter did not manage rebuilding the cards? very confusing error)
=> Fix search ride

test/widgets/home_page_test.dart, test/widgets/profile/profile_page_test.dart, test/widgets/search_ride_page_test.dart, test/widgets/settings/settings_page_test.dart
Kind of picking up the last easy bits of coverage. Also, I refactored the Profile Page Test because it was inconsistent on GitHub (but, weirdly, not locally). It remains to be seen if that works!
=> Low hanging fruit

lib/drives/pages/drive_chat_page.dart, test/widgets/chat/drive_chat_page_test.dart
=> Improve chat preview

lib/l10n/app_de.arb, lib/l10n/app_en.arb, lib/main.dart, test/widgets/main_test.dart
This is the flutter PR for the blocking of a User. The only thing that happens here is that a user that is blocked can't sign in anymore. The Important part of this functionality will be in the corresponding admin PR, which can be found [here](https://github.com/MOTIS-Mitfahr-App/react-web/pull/6).
=> Block user

lib/util/trip/drive_card.dart, lib/util/trip/recurring_drive_empty_card.dart, lib/util/trip/ride_card.dart, lib/util/trip/trip_card.dart, test/widgets/cards_test.dart
adds notification icons for the cards in the top right
the price is only shown on the preview cards for the search
are you happy with the icon choices?
=> Card notification icons

lib/home/pages/home_page.dart, lib/home/widgets/dismissible_list_tile.dart
When dismissing, the background is green and shows an Icon. 
(also refactors duplicate code into DismissibleListTile)
=> Dismissible background
